# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-06-18 13:51:28
"""
import arcpy
import os

def FeatureClassGenerator(workspace, wild_card, feature_type, recursive) :
  with arcpy.EnvManager(workspace = workspace):

    dataset_list = [""]
    if recursive:
      datasets = arcpy.ListDatasets()
      dataset_list.extend(datasets)

    for dataset in dataset_list:
      featureclasses = arcpy.ListFeatureClasses(wild_card, feature_type, dataset)
      for fc in featureclasses:
        yield os.path.join(workspace, dataset, fc), fc

def HAC():  # Yearly Human Actitvity Center modelling using LISA analysis

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\GeoAnalytics Desktop Tools.tbx")
    main_files = "C:\\Users\\erfan\\UNC Charlotte Dropbox\\Erfan Kefayat\\Researches\\Erfan Dissertation\\Data\\Histoical_tax_data\\main_files"

    for FeatureClass, Name in FeatureClassGenerator(main_files, "", "", "NOT_RECURSIVE"):

        # Process: Feature To Point (Feature To Point) (management)
        Name = "tax_2011"
        _Name_Point = fr"C:\Users\erfan\UNC Charlotte Dropbox\Erfan Kefayat\Researches\Erfan Dissertation\Data\Histoical_tax_data\tax.gdb\tax\{Name}_Point"
        arcpy.management.FeatureToPoint(in_features=FeatureClass, out_feature_class=_Name_Point)

        # Process: Copy Features (Copy Features) (management)
        _Name_ = fr"C:\Users\erfan\UNC Charlotte Dropbox\Erfan Kefayat\Researches\Erfan Dissertation\Data\Histoical_tax_data\tax.gdb\tax\{Name}"
        arcpy.management.CopyFeatures(in_features=FeatureClass, out_feature_class=_Name_)

        # Process: Add Field (2) (Add Field) (management)
        tax_2010 = arcpy.management.AddField(in_table=_Name_, field_name="Area_acre", field_type="DOUBLE")[0]

        # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
        tax_2010_3_ = arcpy.management.CalculateGeometryAttributes(in_features=tax_2010, geometry_property=[["Area_acre", "AREA"]], area_unit="ACRES_US", coordinate_system="PROJCS[\"NAD_1983_StatePlane_North_Carolina_FIPS_3200_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",2000000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-79.0],PARAMETER[\"Standard_Parallel_1\",34.3333333333333],PARAMETER[\"Standard_Parallel_2\",36.1666666666667],PARAMETER[\"Latitude_Of_Origin\",33.75],UNIT[\"Foot_US\",0.3048006096012192]]")[0]

        # Process: Add Field (Add Field) (management)
        tax_2010_temp1 = arcpy.management.AddField(in_table=tax_2010_3_, field_name="lv_acre", field_type="DOUBLE")[0]

        # Process: Calculate Field (3) (Calculate Field) (gapro)
        _Name_updated = fr"C:\Users\erfan\UNC Charlotte Dropbox\Erfan Kefayat\Researches\Erfan Dissertation\Data\Histoical_tax_data\tax.gdb\tax\{Name}_updated"
        arcpy.gapro.CalculateField(input_layer=tax_2010_temp1, output=_Name_updated, field_to_calculate="EXISTING_FIELD", existing_field="lv_acre", expression="$feature.LandValue / $feature.Area_acre")

        # Process: Hot Spot Analysis (Getis-Ord Gi*) (Hot Spot Analysis (Getis-Ord Gi*)) (stats)
        _Name_Lisa_2_ = fr"C:\Users\erfan\UNC Charlotte Dropbox\Erfan Kefayat\Researches\Erfan Dissertation\Data\Histoical_tax_data\tax.gdb\tax\{Name}_Lisa"
        Results_Field, Probability_Field, Source_ID = arcpy.stats.HotSpots(Input_Feature_Class=_Name_updated, Input_Field="lv_acre", Output_Feature_Class=_Name_Lisa_2_, Conceptualization_of_Spatial_Relationships="INVERSE_DISTANCE", Distance_Method="EUCLIDEAN_DISTANCE", Standardization="ROW")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\erfan\\UNC Charlotte Dropbox\\Erfan Kefayat\\Researches\\Erfan Dissertation\\GIS\\GIS.gdb", workspace="C:\\Users\\erfan\\UNC Charlotte Dropbox\\Erfan Kefayat\\Researches\\Erfan Dissertation\\GIS\\GIS.gdb"):
        HAC()
